# Change limitation of method length
MethodLength:
  CountComments: true  # count full line comments?
  Max: 20

# Change limitation of AbcSize
AbcSize:
  Max: 27

# Change Line length
LineLength:
  Max: 250
